### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by greenled**
Hi @tortuetorche.

This is a PR to `1-0-next`, a branch I created to keep polishing the Bash version and **eventually** (no hurries) merge it into a `1-0-stable` branch (still to be created when `v1.0.0` is released). It contains your latest changes to `psu` and `Dockerfile` files, and some changes to `Readme.md` too. I though you would be short of time so, I cleaned the history a bit by myself . Changes related with CI and Docs were intentionally left out for later, let's address those topics on different issues and PRs. Let's continue here the non-ci discussion rather than in #4. Please check everything is ok and if we are good to go, merge. This not a `v1.0.0` yet, but it's on its way.

### CODE REVIEW

**Comment by greenled** [comment]
Hey @tortuetorche are you still interested on this MR?

**Comment by tortuetorche** [comment]
Hi @greenled,

Yes I'm!
I just need to find some time to work on this and also test and include changes from #33 

Have a good day,
Tortue Torche

**Comment by greenled** [comment]
Ok, looking forward for your work.

**Comment by tortuetorche** [comment]
Hi @greenled ,

I push some commits, but it's still WIP, I need to test the Vincenzo Cerbone commits (#33)

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi @greenled,

This pull request is now complete!

So feel free to merge it.

Cheers,
Tortue Torche

**Comment by greenled** [comment]
Hi @tortuetorche Sorry, I've been pretty busy and unresponsive these weeks, my bad. I'm looking at your work. Regards.

**Pull request closed without merging**
